"""empty message

Revision ID: 1b19497ee106
Revises: 
Create Date: 2021-03-30 04:52:10.133467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b19497ee106'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('client_id', sa.Integer(), nullable=False))
    op.add_column('subscriptions', sa.Column('nutritionist_id', sa.Integer(), nullable=False))
    op.drop_constraint('subscriptions_nutritionist_fkey', 'subscriptions', type_='foreignkey')
    op.drop_constraint('subscriptions_client_fkey', 'subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'subscriptions', 'nutritionists', ['nutritionist_id'], ['id'])
    op.create_foreign_key(None, 'subscriptions', 'clients', ['client_id'], ['id'])
    op.drop_column('subscriptions', 'client')
    op.drop_column('subscriptions', 'nutritionist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('nutritionist', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('subscriptions', sa.Column('client', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.create_foreign_key('subscriptions_client_fkey', 'subscriptions', 'clients', ['client'], ['id'])
    op.create_foreign_key('subscriptions_nutritionist_fkey', 'subscriptions', 'nutritionists', ['nutritionist'], ['id'])
    op.drop_column('subscriptions', 'nutritionist_id')
    op.drop_column('subscriptions', 'client_id')
    # ### end Alembic commands ###
