"""empty message

Revision ID: 2a6372e1f717
Revises: 1b19497ee106
Create Date: 2021-03-30 06:48:23.526230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a6372e1f717'
down_revision = '1b19497ee106'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('nutritionist_id', sa.Integer(), nullable=False))
    op.drop_constraint('articles_nutritionist_fkey', 'articles', type_='foreignkey')
    op.create_foreign_key(None, 'articles', 'nutritionists', ['nutritionist_id'], ['id'])
    op.drop_column('articles', 'nutritionist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('nutritionist', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.create_foreign_key('articles_nutritionist_fkey', 'articles', 'nutritionists', ['nutritionist'], ['id'])
    op.drop_column('articles', 'nutritionist_id')
    # ### end Alembic commands ###
